# Generated by Django 4.1.4 on 2023-01-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usersapp', '0002_rename_emai_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('repo_link', models.URLField()),
                ('users', models.ManyToManyField(to='Usersapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('project', models.ManyToManyField(to='todolist.project')),
                ('user', models.ManyToManyField(to='Usersapp.user')),
            ],
        ),
    ]
