# Generated by Django 4.1.4 on 2022-12-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emai',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='category',
            new_name='user_name',
        ),
    ]
